# ========================
# DATABASE CONFIGURATION
# ========================
spring.datasource.url=jdbc:postgresql://192.168.18.210:5432/ticketing
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ========================
# SERVER
# ========================
server.port=8080
