package com.itsm.ticketing.config;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

/**
 * One-time database migration to update CHECK constraints on enum columns
 * after adding new {@link com.itsm.ticketing.entity.Role} values
 * (SUPPORT, TECHNICAL_SUPPORT), and to create the notification-related
 * table {@code ticket_user_reads} used by the server-side read receipt system.
 *
 * <p>Each statement uses {@code DROP CONSTRAINT IF EXISTS} / {@code CREATE TABLE IF NOT EXISTS}
 * so it is safe to run multiple times. This can be removed once the deployed environment
 * has applied all the constraints.</p>
 */
@Configuration
@Slf4j
public class DatabaseMigrationConfig {

    private static final String VALID_ROLES = "'ADMIN', 'SUPPORT', 'TECHNICAL_SUPPORT', 'USER'";

    @Bean
    public CommandLineRunner migrateRoleConstraint(DataSource dataSource) {
        return args -> {
            try (Connection conn = dataSource.getConnection();
                 Statement stmt = conn.createStatement()) {

                log.info("Applying role CHECK-constraint migrations ...");

                // -------------------------------------------------------------
                // users.role
                // -------------------------------------------------------------
                stmt.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check");
                stmt.execute(
                        "ALTER TABLE users ADD CONSTRAINT users_role_check "
                                + "CHECK (role IN (" + VALID_ROLES + "))");
                log.info("users.role constraint OK: {}", VALID_ROLES);

                // -------------------------------------------------------------
                // chat_messages.sender_role  (auto-generated by Hibernate when
                // the enum had only ADMIN/USER, blocks SUPPORT/TECHNICAL_SUPPORT
                // from sending messages)
                // -------------------------------------------------------------
                stmt.execute("ALTER TABLE chat_messages DROP CONSTRAINT IF EXISTS chat_messages_sender_role_check");
                stmt.execute(
                        "ALTER TABLE chat_messages ADD CONSTRAINT chat_messages_sender_role_check "
                                + "CHECK (sender_role IN (" + VALID_ROLES + "))");
                log.info("chat_messages.sender_role constraint OK: {}", VALID_ROLES);

                // -------------------------------------------------------------
                // ticket_progress_logs (the changed_by_role column may carry
                // the same enum check). Skip silently if the table/column
                // does not exist.
                // -------------------------------------------------------------
                try {
                    stmt.execute("ALTER TABLE ticket_progress_logs DROP CONSTRAINT IF EXISTS ticket_progress_logs_changed_by_role_check");
                    stmt.execute(
                            "ALTER TABLE ticket_progress_logs ADD CONSTRAINT ticket_progress_logs_changed_by_role_check "
                                    + "CHECK (changed_by_role IN (" + VALID_ROLES + "))");
                    log.info("ticket_progress_logs.changed_by_role constraint OK: {}", VALID_ROLES);
                } catch (Exception ignored) {
                    log.debug("ticket_progress_logs.changed_by_role constraint skipped (column may not exist)");
                }

                // -------------------------------------------------------------
                // ticket_user_reads — server-side read receipt table.
                // Composite PK (ticket_id, user_id) + last_read_at watermark.
                // Safe to run multiple times due to IF NOT EXISTS.
                // -------------------------------------------------------------
                stmt.execute("""
                        CREATE TABLE IF NOT EXISTS ticket_user_reads (
                            ticket_id    BIGINT NOT NULL,
                            user_id      BIGINT NOT NULL,
                            last_read_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                            PRIMARY KEY (ticket_id, user_id),
                            CONSTRAINT fk_tur_ticket FOREIGN KEY (ticket_id)
                                REFERENCES tickets(id) ON DELETE CASCADE,
                            CONSTRAINT fk_tur_user FOREIGN KEY (user_id)
                                REFERENCES users(id) ON DELETE CASCADE
                        )
                        """);
                log.info("ticket_user_reads table created or already exists");

                // -------------------------------------------------------------
                // ticket_progress_logs.changed_by — make nullable to support
                // system-initiated status changes (e.g. auto-close scheduler).
                // Uses ALTER COLUMN … DROP NOT NULL which is idempotent on
                // PostgreSQL (no-op if already nullable).
                // -------------------------------------------------------------
                try {
                    stmt.execute(
                            "ALTER TABLE ticket_progress_logs "
                                    + "ALTER COLUMN changed_by DROP NOT NULL");
                    log.info("ticket_progress_logs.changed_by nullable migration OK");
                } catch (Exception ignored) {
                    log.debug("ticket_progress_logs.changed_by nullable migration skipped (already nullable or not applicable)");
                }

            } catch (Exception e) {
                log.warn("Role constraint migration skipped or partially applied: {}", e.getMessage());
            }
        };
    }
}
